services:
  local_postgres:
    image: postgres:15
    container_name: local_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pdb
    ports:
      - "8212:5432"
    restart: always
    networks:
      - yensi_docker_network
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data

  local_keycloak:
    image: quay.io/keycloak/keycloak:26.0.1
    container_name: local_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://local_postgres/pdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - start-dev
      - "--features=docker,token-exchange,admin-fine-grained-authz"
      - "--import-realm"
    restart: always
    depends_on:
      - local_postgres
    networks:
      - yensi_docker_network
    volumes:
      - ./volumes/keycloak-config:/opt/keycloak/keycloak-config
      - ./KeycloakTheme:/opt/keycloak/themes/
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: jewelleryApi
    command: mongod --auth
    ports:
      - "57057:27017"
    networks:
      - yensi_docker_network
    volumes:
      - ./volumes/mongo/data:/data/db
      - ./volumes/mongo/config:/data/configdb

networks:
  yensi_docker_network:
    external: true
