adminEmail = "admin@example.com"
adminPassword = "asdfgh"
username = "admin"
role = "Admin"

serverUrl = "http://localhost:8000"
registerUrl = f"{serverUrl}/register"
loginUrl = f"{serverUrl}/login"
CATEGORY_URL = f"{serverUrl}/admin/categories"
PRODUCT_URL = f"{serverUrl}/admin/product/create"
UPLOAD_URL = f"{serverUrl}/upload-file"
